name: bella_mall
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.6.0
  cupertino_icons: ^0.1.3
  font_awesome_flutter: ^8.1.0
  flutter_barcode_scanner: ^1.0.0
  simple_animations: ^1.3.3
  sqflite: ^1.0.0
  path_provider: ^1.0.2
  path: ^1.8.0
  url_launcher: ^6.0.6
  firebase_core: ^1.5.0
  firebase_database: ^7.1.1
  custom_dialog: ^0.0.2
  firebase_storage: ^9.0.0
  firebase_analytics: ^5.0.6
  toast: ^0.1.5
  image_cropper: ^1.4.1
  flutter_launcher_icons: ^0.9.0
  cloud_firestore:
  image: ^3.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
     - image/

flutter_launcher_icons:
  path: ../

flutter_icons:
  image_path_android: "image/iconBellaMall.png"
  android: true
  image_path: "image/iconBellaMall.png"
  adaptive_icon_background: "image/iconBellaMall.png"
  adaptive_icon_foreground: "image/iconBellaMall.png"

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
